// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIy4tUSsTfkJNKC5V3zedxHFSu4tBAAjM',
    appId: '1:861502621099:web:59d62da86ec0f30f98beee',
    messagingSenderId: '861502621099',
    projectId: 'a-24315',
    authDomain: 'a-24315.firebaseapp.com',
    storageBucket: 'a-24315.appspot.com',
    measurementId: 'G-S6FVGXQ8TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTvtCqd-QPYLntY6euMJbW6ZOjCRIsHis',
    appId: '1:861502621099:android:b91b1e7e2346a28c98beee',
    messagingSenderId: '861502621099',
    projectId: 'a-24315',
    storageBucket: 'a-24315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7XM2aJwmq2p9pHZZqd2TgA7TI-DAhYSQ',
    appId: '1:861502621099:ios:a6f19756c8f6375b98beee',
    messagingSenderId: '861502621099',
    projectId: 'a-24315',
    storageBucket: 'a-24315.appspot.com',
    iosClientId: '861502621099-50fuujholv15vc4iqnq87q91e1drnck1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7XM2aJwmq2p9pHZZqd2TgA7TI-DAhYSQ',
    appId: '1:861502621099:ios:a6f19756c8f6375b98beee',
    messagingSenderId: '861502621099',
    projectId: 'a-24315',
    storageBucket: 'a-24315.appspot.com',
    iosClientId: '861502621099-50fuujholv15vc4iqnq87q91e1drnck1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezText',
  );
}
