// Mocks generated by Mockito 5.4.2 from annotations
// in ez_text/test/addFriend_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:ez_text/models/user_model.dart' as _i4;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

import '../addFriend_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

class _FakeUserCredential_1 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_1(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

class _FakeUserModel_2 extends _i1.SmartFake implements _i4.UserModel {
  _FakeUserModel_2(
      Object parent,
      Invocation parentInvocation,
      ) : super(
    parent,
    parentInvocation,
  );
}

/// A class which mocks [AddFriendsTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i5.AddFriendsTest {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<_i4.UserModel> get userRef => (super.noSuchMethod(
    Invocation.getter(#userRef),
    returnValue: _FakeCollectionReference_0<_i4.UserModel>(
      this,
      Invocation.getter(#userRef),
    ),
  ) as _i2.CollectionReference<_i4.UserModel>);
  @override
  set userRef(_i2.CollectionReference<_i4.UserModel>? _userRef) =>
      super.noSuchMethod(
        Invocation.setter(
          #userRef,
          _userRef,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<_i3.UserCredential?> register(_i4.UserModel? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [user],
        ),
        returnValue: _i6.Future<_i3.UserCredential?>.value(),
      ) as _i6.Future<_i3.UserCredential?>);
  @override
  _i6.Future<_i3.UserCredential> login(
      String? email,
      String? password,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i3.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i3.UserCredential>);
  @override
  _i6.Future<_i4.UserModel> getUserDetail(String? uid) => (super.noSuchMethod(
    Invocation.method(
      #getUserDetail,
      [uid],
    ),
    returnValue: _i6.Future<_i4.UserModel>.value(_FakeUserModel_2(
      this,
      Invocation.method(
        #getUserDetail,
        [uid],
      ),
    )),
  ) as _i6.Future<_i4.UserModel>);
  @override
  _i6.Future<_i4.UserModel> getUserDetailWithEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailWithEmail,
          [email],
        ),
        returnValue: _i6.Future<_i4.UserModel>.value(_FakeUserModel_2(
          this,
          Invocation.method(
            #getUserDetailWithEmail,
            [email],
          ),
        )),
      ) as _i6.Future<_i4.UserModel>);
  @override
  _i6.Future<_i4.UserModel> getUserDetailWithId(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailWithId,
          [id],
        ),
        returnValue: _i6.Future<_i4.UserModel>.value(_FakeUserModel_2(
          this,
          Invocation.method(
            #getUserDetailWithId,
            [id],
          ),
        )),
      ) as _i6.Future<_i4.UserModel>);
  @override
  _i6.Future<_i4.UserModel?> addUser(
      _i4.UserModel? model,
      String? id,
      String? email,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [
            model,
            id,
            email,
          ],
        ),
        returnValue: _i6.Future<_i4.UserModel?>.value(),
      ) as _i6.Future<_i4.UserModel?>);
  @override
  _i6.Future<_i4.UserModel?> addFavorite(
      _i4.UserModel? model,
      String? id,
      String? email,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            model,
            id,
            email,
          ],
        ),
        returnValue: _i6.Future<_i4.UserModel?>.value(),
      ) as _i6.Future<_i4.UserModel?>);
  @override
  _i6.Future<_i4.UserModel?> removeFavorite(
      _i4.UserModel? model,
      String? id,
      String? email,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [
            model,
            id,
            email,
          ],
        ),
        returnValue: _i6.Future<_i4.UserModel?>.value(),
      ) as _i6.Future<_i4.UserModel?>);
  @override
  _i6.Future<bool> changePassword(
      String? password,
      String? id,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            password,
            id,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<void> removeFriend(
      String? loggedIn,
      String? friendId,
      ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [
            loggedIn,
            friendId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}